# POST http://localhost:4000/api/auth/signupRestaurant
# Content-Type: application/json

# {
#   "email": "emanuel@gmail.com",
#   "password": "Laca1234@#$&",
#   "name": "Emmanuel Anyigor",
#   "phone": "+2347061326122"
# }
# POST http://localhost:4000/api/auth/signupUser
# Content-Type: application/json

# {
#   "email": "email@gmail.com",
#   "password": "Laca1234@#$&",
#   "name": "Emmanuel Anyigor",
#   "phone": "+2347061326122"
# }

POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "email": "emanuel@gmail.com",
  "password": "Laca1234@#$&"
}
