POST http://localhost:4000/api/auth/verifyEmail
Content-Type: application/json

{
  "email": "emanuelanyigor@gmail.com",
  "code": "7377"
}
# POST http://localhost:4000/api/auth/ResetPassword
# Content-Type: application/json

# {
#   "email": "emanuelanyigor@gmail.com",
#   "password": "Test@123",
#   "code": "0848"
# }


# POST http://localhost:4000/api/auth/forgotPassword
# Content-Type: application/json

# {
#   "email": "emanuelanyigor@gmail.com"
# }

# POST http://localhost:4000/api/auth/signupRestaurant
# Content-Type: application/json

# {
#   "email": "emanuelanyigor@gmail.com",
#   "password": "Laca1234@#$&",
#   "name": "Emmanuel Anyigor2",
#   "phone": "+2347061326122"
# }
# POST http://localhost:4000/api/auth/signupUser
# Content-Type: application/json

# {
#   "email": "email@gmail.com",
#   "password": "Laca1234@#$&",
#   "name": "Emmanuel Anyigor",
#   "phone": "+2347061326122"
# }


# POST https://foodgo-server.onrender.com/api/auth/loginUser
# Content-Type: application/json

# {
#   "email": "Jane@gmail.com",
#   "password": "Laca1234@#$&"
# }

# POST https://foodgo-server.onrender.com/api/auth/signupRestaurant
# Content-Type: application/json

# {
#   "email": "xanix123@gmail.com",
#   "password": "Laca1234@#$&",
#   "name": "Burger Burito",
#   "phone": "+2347061326122"
# }

# GET http://localhost:4000/api/user/
# Content-Type: application/json
# x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzZmMTAyZTEzZDUyY2NjYzZlZDczNDUiLCJuYW1lIjoiRW1tYW51ZWwgQW55aWdvciIsImlzX3VzZXIiOnRydWUsImlzX2VtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiaWF0IjoxNzM1NDIzMTkwLCJleHAiOjE3MzU1MDk1OTB9.TGCpk-W-6iI0m8EshNfDZOVzLU_j2C7PV_Z5hYTg5S8

# DELETE http://localhost:4000/api/user/
# Content-Type: application/json
# x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzZmMTAyZTEzZDUyY2NjYzZlZDczNDUiLCJuYW1lIjoiRW1tYW51ZWwgQW55aWdvciIsImlzX3VzZXIiOnRydWUsImlzX2VtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiaWF0IjoxNzM1NDIzMTkwLCJleHAiOjE3MzU1MDk1OTB9.TGCpk-W-6iI0m8EshNfDZOVzLU_j2C7PV_Z5hYTg5S8

# PUT http://localhost:4000/api/user/
# Content-Type: application/json
# x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzZmMTAyZTEzZDUyY2NjYzZlZDczNDUiLCJuYW1lIjoiRW1tYW51ZWwgQW55aWdvciIsImlzX3VzZXIiOnRydWUsImlzX2VtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiaWF0IjoxNzM1NDIzMTkwLCJleHAiOjE3MzU1MDk1OTB9.TGCpk-W-6iI0m8EshNfDZOVzLU_j2C7PV_Z5hYTg5S8

# {
#   "name": "Anyigor",
#   "state": "Lagos",
#   "email": "email@gmail.com",
#   "phone": "07088945911",
#   "about": "Certified Hacker",
#   "city": "Ikorodu",
#   "street": "Shakiru Yusuf Street",
#   "zipcode": 102321,
#   "longitude": 12.8503505,
#   "latitude": 18.2895
# }